/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { TransferWithAllowance64_64TestsContract } from "./TransferWithAllowance64_64TestsContract";
export type { TransferWithAllowance64_8TestsContract } from "./TransferWithAllowance64_8TestsContract";
