/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../common";
import type {
  MpcAbiCodec,
  MpcAbiCodecInterface,
} from "../../../../contracts/pod/mpccodec/MpcAbiCodec";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint8",
        name: "dataType",
        type: "uint8",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "argLen",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "argHash",
        type: "bytes32",
      },
    ],
    name: "ValidateCiphertextStart",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint8",
        name: "dataType",
        type: "uint8",
      },
    ],
    name: "ValidateCiphertextSuccess",
    type: "event",
  },
] as const;

const _bytecode =
  "0x6080806040523460175760109081601c823930815050f35b5f80fdfe5f80fdfea164736f6c634300081c000a";

type MpcAbiCodecConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: MpcAbiCodecConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class MpcAbiCodec__factory extends ContractFactory {
  constructor(...args: MpcAbiCodecConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      MpcAbiCodec & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): MpcAbiCodec__factory {
    return super.connect(runner) as MpcAbiCodec__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MpcAbiCodecInterface {
    return new Interface(_abi) as MpcAbiCodecInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): MpcAbiCodec {
    return new Contract(address, _abi, runner) as unknown as MpcAbiCodec;
  }
}
