/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  InboxUser,
  InboxUserInterface,
} from "../../../contracts/pod/InboxUser";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "caller",
        type: "address",
      },
    ],
    name: "OnlyInbox",
    type: "error",
  },
  {
    inputs: [],
    name: "inbox",
    outputs: [
      {
        internalType: "contract IInbox",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class InboxUser__factory {
  static readonly abi = _abi;
  static createInterface(): InboxUserInterface {
    return new Interface(_abi) as InboxUserInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): InboxUser {
    return new Contract(address, _abi, runner) as unknown as InboxUser;
  }
}
