/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { TransferWithAllowance64_64TestsContract__factory } from "./TransferWithAllowance64_64TestsContract__factory";
export { TransferWithAllowance64_8TestsContract__factory } from "./TransferWithAllowance64_8TestsContract__factory";
