/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ExamplePrivateERC20 } from "./ExamplePrivateERC20";
export type { ExamplePrivateERC20Mock } from "./ExamplePrivateERC20Mock";
