/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { FixedRatioCoinDisperserUnlimitedWindow__factory } from "./FixedRatioCoinDisperserUnlimitedWindow__factory";
