/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../../common";
import type {
  Shift256TestsContract,
  Shift256TestsContractInterface,
} from "../../../../../contracts/mocks/utils/mpc/Shift256TestsContract";

const _abi = [
  {
    inputs: [],
    name: "getShlResult",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getShrResult",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "a",
        type: "uint256",
      },
      {
        internalType: "uint8",
        name: "shift",
        type: "uint8",
      },
    ],
    name: "shlTest",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "a",
        type: "uint256",
      },
      {
        internalType: "uint8",
        name: "shift",
        type: "uint8",
      },
    ],
    name: "shrTest",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b5061036b806100206000396000f3fe608060405234801561001057600080fd5b506004361061004c5760003560e01c806308c36b63146100515780635e1f73b6146100765780637f7e6b941461007e5780638c18b2e514610091575b600080fd5b61006461005f3660046102e0565b610099565b60405190815260200160405180910390f35b600154610064565b61006461008c3660046102e0565b6100c9565b600054610064565b6000806100a5846100f4565b905060006100bb6100b68386610197565b610260565b600081905595945050505050565b6000806100d5846100f4565b905060006100e66100b68386610270565b600181905595945050505050565b6000606463d9b60b6060065b60f81b846040518363ffffffff1660e01b815260040161014e9291907fff00000000000000000000000000000000000000000000000000000000000000929092168252602082015260400190565b6020604051808303816000875af115801561016d573d6000803e3d6000fd5b505050506040513d601f19601f820116820180604052508101906101919190610345565b92915050565b60006064631135f71a6101ae600660016002610283565b6040517fffffffff0000000000000000000000000000000000000000000000000000000060e084901b1681527fffffff000000000000000000000000000000000000000000000000000000000090911660048201526024810186905260ff851660448201526064016020604051808303816000875af1158015610235573d6000803e3d6000fd5b505050506040513d601f19601f820116820180604052508101906102599190610345565b9392505050565b60006064630cfed5616006610100565b600060646339bd1d8d6101ae6006600160025b600081600281111561029757610297610316565b60ff1660088460068111156102ae576102ae610316565b61ffff16901b61ffff1660108660068111156102cc576102cc610316565b62ffffff16901b171760e81b949350505050565b600080604083850312156102f357600080fd5b82359150602083013560ff8116811461030b57600080fd5b809150509250929050565b7f4e487b7100000000000000000000000000000000000000000000000000000000600052602160045260246000fd5b60006020828403121561035757600080fd5b505191905056fea164736f6c6343000813000a";

type Shift256TestsContractConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: Shift256TestsContractConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class Shift256TestsContract__factory extends ContractFactory {
  constructor(...args: Shift256TestsContractConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      Shift256TestsContract & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(
    runner: ContractRunner | null
  ): Shift256TestsContract__factory {
    return super.connect(runner) as Shift256TestsContract__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): Shift256TestsContractInterface {
    return new Interface(_abi) as Shift256TestsContractInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): Shift256TestsContract {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as Shift256TestsContract;
  }
}
