/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IERC7984PortalWrapper,
  IERC7984PortalWrapperInterface,
} from "../../../../../contracts/pod/token/erc7984/IERC7984PortalWrapper";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "receiver",
        type: "address",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "unwrapRequestId",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "encryptedAmount",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "uint64",
        name: "cleartextAmount",
        type: "uint64",
      },
    ],
    name: "UnwrapFinalized",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "receiver",
        type: "address",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "unwrapRequestId",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "amount",
        type: "bytes32",
      },
    ],
    name: "UnwrapRequested",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "mintRequestId",
        type: "bytes32",
      },
    ],
    name: "WrapRequested",
    type: "event",
  },
  {
    inputs: [],
    name: "rate",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "underlying",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "mintCallbackFee",
        type: "uint256",
      },
    ],
    name: "wrap",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "payable",
    type: "function",
  },
] as const;

export class IERC7984PortalWrapper__factory {
  static readonly abi = _abi;
  static createInterface(): IERC7984PortalWrapperInterface {
    return new Interface(_abi) as IERC7984PortalWrapperInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IERC7984PortalWrapper {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IERC7984PortalWrapper;
  }
}
