/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../../common";

export type PortalFeeConfigStruct = {
  fixedFee: BigNumberish;
  percentageBps: BigNumberish;
  maxFee: BigNumberish;
};

export type PortalFeeConfigStructOutput = [
  fixedFee: bigint,
  percentageBps: bigint,
  maxFee: bigint
] & { fixedFee: bigint; percentageBps: bigint; maxFee: bigint };

export interface MockPrivacyPortalFactoryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "decodeFeeConfig"
      | "defaultDepositFeePacked"
      | "defaultWithdrawFeePacked"
      | "depositsPaused"
      | "estimateDepositPortalFee"
      | "estimateWithdrawPortalFee"
      | "feeRecipient"
      | "getDepositPortalFeeFloor"
      | "getFeeConfig"
      | "getWithdrawPortalFeeFloor"
      | "nativeToken"
      | "priceOracle"
      | "setDepositsPaused"
      | "setWithdrawalsPaused"
      | "withdrawalsPaused"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "decodeFeeConfig",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "defaultDepositFeePacked",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "defaultWithdrawFeePacked",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "depositsPaused",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "estimateDepositPortalFee",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "estimateWithdrawPortalFee",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "feeRecipient",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getDepositPortalFeeFloor",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getFeeConfig",
    values: [boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "getWithdrawPortalFeeFloor",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "nativeToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "priceOracle",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setDepositsPaused",
    values: [boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setWithdrawalsPaused",
    values: [boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawalsPaused",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "decodeFeeConfig",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "defaultDepositFeePacked",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "defaultWithdrawFeePacked",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositsPaused",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "estimateDepositPortalFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "estimateWithdrawPortalFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "feeRecipient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDepositPortalFeeFloor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFeeConfig",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getWithdrawPortalFeeFloor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nativeToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "priceOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDepositsPaused",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setWithdrawalsPaused",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawalsPaused",
    data: BytesLike
  ): Result;
}

export interface MockPrivacyPortalFactory extends BaseContract {
  connect(runner?: ContractRunner | null): MockPrivacyPortalFactory;
  waitForDeployment(): Promise<this>;

  interface: MockPrivacyPortalFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  decodeFeeConfig: TypedContractMethod<
    [packed: BytesLike],
    [PortalFeeConfigStructOutput],
    "view"
  >;

  defaultDepositFeePacked: TypedContractMethod<[], [string], "view">;

  defaultWithdrawFeePacked: TypedContractMethod<[], [string], "view">;

  depositsPaused: TypedContractMethod<[], [boolean], "view">;

  estimateDepositPortalFee: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish, arg2: BigNumberish],
    [[bigint, boolean] & { fee: bigint; usedDynamicPricing: boolean }],
    "view"
  >;

  estimateWithdrawPortalFee: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish, arg2: BigNumberish],
    [[bigint, boolean] & { fee: bigint; usedDynamicPricing: boolean }],
    "view"
  >;

  feeRecipient: TypedContractMethod<[], [string], "view">;

  getDepositPortalFeeFloor: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish, arg2: BigNumberish],
    [[bigint, bigint] & { floor: bigint; maxFee: bigint }],
    "view"
  >;

  getFeeConfig: TypedContractMethod<
    [isDeposit: boolean],
    [PortalFeeConfigStructOutput],
    "view"
  >;

  getWithdrawPortalFeeFloor: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish, arg2: BigNumberish],
    [[bigint, bigint] & { floor: bigint; maxFee: bigint }],
    "view"
  >;

  nativeToken: TypedContractMethod<[], [string], "view">;

  priceOracle: TypedContractMethod<[], [string], "view">;

  setDepositsPaused: TypedContractMethod<
    [paused: boolean],
    [void],
    "nonpayable"
  >;

  setWithdrawalsPaused: TypedContractMethod<
    [paused: boolean],
    [void],
    "nonpayable"
  >;

  withdrawalsPaused: TypedContractMethod<[], [boolean], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "decodeFeeConfig"
  ): TypedContractMethod<
    [packed: BytesLike],
    [PortalFeeConfigStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "defaultDepositFeePacked"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "defaultWithdrawFeePacked"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "depositsPaused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "estimateDepositPortalFee"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish, arg2: BigNumberish],
    [[bigint, boolean] & { fee: bigint; usedDynamicPricing: boolean }],
    "view"
  >;
  getFunction(
    nameOrSignature: "estimateWithdrawPortalFee"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish, arg2: BigNumberish],
    [[bigint, boolean] & { fee: bigint; usedDynamicPricing: boolean }],
    "view"
  >;
  getFunction(
    nameOrSignature: "feeRecipient"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getDepositPortalFeeFloor"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish, arg2: BigNumberish],
    [[bigint, bigint] & { floor: bigint; maxFee: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getFeeConfig"
  ): TypedContractMethod<
    [isDeposit: boolean],
    [PortalFeeConfigStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getWithdrawPortalFeeFloor"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish, arg2: BigNumberish],
    [[bigint, bigint] & { floor: bigint; maxFee: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "nativeToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "priceOracle"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setDepositsPaused"
  ): TypedContractMethod<[paused: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setWithdrawalsPaused"
  ): TypedContractMethod<[paused: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawalsPaused"
  ): TypedContractMethod<[], [boolean], "view">;

  filters: {};
}
