/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IPrivacyPortalFactory__factory } from "./IPrivacyPortalFactory__factory";
export { IPrivacyPortalPauseController__factory } from "./IPrivacyPortalPauseController__factory";
