/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IPrivacyPortalPauseController,
  IPrivacyPortalPauseControllerInterface,
} from "../../../../../contracts/pod/privacy/IPrivacyPortalFactory.sol/IPrivacyPortalPauseController";

const _abi = [
  {
    inputs: [],
    name: "depositsPaused",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "withdrawalsPaused",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IPrivacyPortalPauseController__factory {
  static readonly abi = _abi;
  static createInterface(): IPrivacyPortalPauseControllerInterface {
    return new Interface(_abi) as IPrivacyPortalPauseControllerInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IPrivacyPortalPauseController {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IPrivacyPortalPauseController;
  }
}
