/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../../common";

export interface Arithmetic128TestsContractInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addTest"
      | "checkedAddTest"
      | "checkedMulTest"
      | "checkedSubTest"
      | "divTest"
      | "getAddResult"
      | "getDivResult"
      | "getMulResult"
      | "getRemResult"
      | "getSubResult"
      | "mulTest"
      | "remTest"
      | "subTest"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "addTest",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "checkedAddTest",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "checkedMulTest",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "checkedSubTest",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "divTest",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAddResult",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getDivResult",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMulResult",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRemResult",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getSubResult",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "mulTest",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "remTest",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "subTest",
    values: [BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "addTest", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "checkedAddTest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkedMulTest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkedSubTest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "divTest", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAddResult",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDivResult",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMulResult",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRemResult",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSubResult",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "mulTest", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "remTest", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "subTest", data: BytesLike): Result;
}

export interface Arithmetic128TestsContract extends BaseContract {
  connect(runner?: ContractRunner | null): Arithmetic128TestsContract;
  waitForDeployment(): Promise<this>;

  interface: Arithmetic128TestsContractInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addTest: TypedContractMethod<
    [a: BigNumberish, b: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  checkedAddTest: TypedContractMethod<
    [a: BigNumberish, b: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  checkedMulTest: TypedContractMethod<
    [a: BigNumberish, b: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  checkedSubTest: TypedContractMethod<
    [a: BigNumberish, b: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  divTest: TypedContractMethod<
    [a: BigNumberish, b: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  getAddResult: TypedContractMethod<[], [bigint], "view">;

  getDivResult: TypedContractMethod<[], [bigint], "view">;

  getMulResult: TypedContractMethod<[], [bigint], "view">;

  getRemResult: TypedContractMethod<[], [bigint], "view">;

  getSubResult: TypedContractMethod<[], [bigint], "view">;

  mulTest: TypedContractMethod<
    [a: BigNumberish, b: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  remTest: TypedContractMethod<
    [a: BigNumberish, b: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  subTest: TypedContractMethod<
    [a: BigNumberish, b: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addTest"
  ): TypedContractMethod<
    [a: BigNumberish, b: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "checkedAddTest"
  ): TypedContractMethod<
    [a: BigNumberish, b: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "checkedMulTest"
  ): TypedContractMethod<
    [a: BigNumberish, b: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "checkedSubTest"
  ): TypedContractMethod<
    [a: BigNumberish, b: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "divTest"
  ): TypedContractMethod<
    [a: BigNumberish, b: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getAddResult"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getDivResult"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getMulResult"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getRemResult"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getSubResult"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "mulTest"
  ): TypedContractMethod<
    [a: BigNumberish, b: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "remTest"
  ): TypedContractMethod<
    [a: BigNumberish, b: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "subTest"
  ): TypedContractMethod<
    [a: BigNumberish, b: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  filters: {};
}
