/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../../common";

export interface CheckedArithmetic128WithOverflowBitTestsContractInterface
  extends Interface {
  getFunction(
    nameOrSignature:
      | "checkedAddWithOverflowBitTest"
      | "checkedMulWithOverflowBitTest"
      | "checkedSubWithOverflowBitTest"
      | "getAddResult"
      | "getMulResult"
      | "getOverflowBit"
      | "getSubResult"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "checkedAddWithOverflowBitTest",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "checkedMulWithOverflowBitTest",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "checkedSubWithOverflowBitTest",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAddResult",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMulResult",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getOverflowBit",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getSubResult",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "checkedAddWithOverflowBitTest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkedMulWithOverflowBitTest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkedSubWithOverflowBitTest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAddResult",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMulResult",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getOverflowBit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSubResult",
    data: BytesLike
  ): Result;
}

export interface CheckedArithmetic128WithOverflowBitTestsContract
  extends BaseContract {
  connect(
    runner?: ContractRunner | null
  ): CheckedArithmetic128WithOverflowBitTestsContract;
  waitForDeployment(): Promise<this>;

  interface: CheckedArithmetic128WithOverflowBitTestsContractInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  checkedAddWithOverflowBitTest: TypedContractMethod<
    [a: BigNumberish, b: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  checkedMulWithOverflowBitTest: TypedContractMethod<
    [a: BigNumberish, b: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  checkedSubWithOverflowBitTest: TypedContractMethod<
    [a: BigNumberish, b: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  getAddResult: TypedContractMethod<[], [bigint], "view">;

  getMulResult: TypedContractMethod<[], [bigint], "view">;

  getOverflowBit: TypedContractMethod<[], [boolean], "view">;

  getSubResult: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "checkedAddWithOverflowBitTest"
  ): TypedContractMethod<
    [a: BigNumberish, b: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "checkedMulWithOverflowBitTest"
  ): TypedContractMethod<
    [a: BigNumberish, b: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "checkedSubWithOverflowBitTest"
  ): TypedContractMethod<
    [a: BigNumberish, b: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getAddResult"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getMulResult"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getOverflowBit"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "getSubResult"
  ): TypedContractMethod<[], [bigint], "view">;

  filters: {};
}
