/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../../common";

export interface Comparison128TestsContractInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "eqTest"
      | "geTest"
      | "getEqResult"
      | "getGeResult"
      | "getGtResult"
      | "getLeResult"
      | "getLtResult"
      | "getNeResult"
      | "gtTest"
      | "leTest"
      | "ltTest"
      | "neTest"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "eqTest",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "geTest",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEqResult",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getGeResult",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getGtResult",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getLeResult",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getLtResult",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getNeResult",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "gtTest",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "leTest",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "ltTest",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "neTest",
    values: [BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "eqTest", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "geTest", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getEqResult",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getGeResult",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getGtResult",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLeResult",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLtResult",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getNeResult",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "gtTest", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "leTest", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "ltTest", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "neTest", data: BytesLike): Result;
}

export interface Comparison128TestsContract extends BaseContract {
  connect(runner?: ContractRunner | null): Comparison128TestsContract;
  waitForDeployment(): Promise<this>;

  interface: Comparison128TestsContractInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  eqTest: TypedContractMethod<
    [a: BigNumberish, b: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  geTest: TypedContractMethod<
    [a: BigNumberish, b: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  getEqResult: TypedContractMethod<[], [boolean], "view">;

  getGeResult: TypedContractMethod<[], [boolean], "view">;

  getGtResult: TypedContractMethod<[], [boolean], "view">;

  getLeResult: TypedContractMethod<[], [boolean], "view">;

  getLtResult: TypedContractMethod<[], [boolean], "view">;

  getNeResult: TypedContractMethod<[], [boolean], "view">;

  gtTest: TypedContractMethod<
    [a: BigNumberish, b: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  leTest: TypedContractMethod<
    [a: BigNumberish, b: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  ltTest: TypedContractMethod<
    [a: BigNumberish, b: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  neTest: TypedContractMethod<
    [a: BigNumberish, b: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "eqTest"
  ): TypedContractMethod<
    [a: BigNumberish, b: BigNumberish],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "geTest"
  ): TypedContractMethod<
    [a: BigNumberish, b: BigNumberish],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getEqResult"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "getGeResult"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "getGtResult"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "getLeResult"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "getLtResult"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "getNeResult"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "gtTest"
  ): TypedContractMethod<
    [a: BigNumberish, b: BigNumberish],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "leTest"
  ): TypedContractMethod<
    [a: BigNumberish, b: BigNumberish],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "ltTest"
  ): TypedContractMethod<
    [a: BigNumberish, b: BigNumberish],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "neTest"
  ): TypedContractMethod<
    [a: BigNumberish, b: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  filters: {};
}
