/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../../common";

export interface ExtendedArithmeticTestsContractInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "checkedMulTest"
      | "checkedMulWithOverflowBitTest"
      | "mulTest"
      | "numbers"
      | "numbersLHS"
      | "numbersRHS"
      | "overflows"
      | "overflowsLHS"
      | "overflowsRHS"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "checkedMulTest",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "checkedMulWithOverflowBitTest",
    values: [BigNumberish[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "mulTest",
    values: [BigNumberish[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "numbers",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "numbersLHS",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "numbersRHS",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "overflows",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "overflowsLHS",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "overflowsRHS",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "checkedMulTest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkedMulWithOverflowBitTest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "mulTest", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "numbers", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "numbersLHS", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "numbersRHS", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "overflows", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "overflowsLHS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "overflowsRHS",
    data: BytesLike
  ): Result;
}

export interface ExtendedArithmeticTestsContract extends BaseContract {
  connect(runner?: ContractRunner | null): ExtendedArithmeticTestsContract;
  waitForDeployment(): Promise<this>;

  interface: ExtendedArithmeticTestsContractInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  checkedMulTest: TypedContractMethod<
    [a: BigNumberish, b: BigNumberish],
    [void],
    "nonpayable"
  >;

  checkedMulWithOverflowBitTest: TypedContractMethod<
    [a: BigNumberish[], b: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  mulTest: TypedContractMethod<
    [a: BigNumberish[], b: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  numbers: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  numbersLHS: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  numbersRHS: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  overflows: TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;

  overflowsLHS: TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;

  overflowsRHS: TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "checkedMulTest"
  ): TypedContractMethod<
    [a: BigNumberish, b: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "checkedMulWithOverflowBitTest"
  ): TypedContractMethod<
    [a: BigNumberish[], b: BigNumberish[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "mulTest"
  ): TypedContractMethod<
    [a: BigNumberish[], b: BigNumberish[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "numbers"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "numbersLHS"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "numbersRHS"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "overflows"
  ): TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "overflowsLHS"
  ): TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "overflowsRHS"
  ): TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;

  filters: {};
}
