/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../../common";

export interface MinMax256TestsContractInterface extends Interface {
  getFunction(
    nameOrSignature: "getMaxResult" | "getMinResult" | "maxTest" | "minTest"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getMaxResult",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMinResult",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "maxTest",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "minTest",
    values: [BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "getMaxResult",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMinResult",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "maxTest", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "minTest", data: BytesLike): Result;
}

export interface MinMax256TestsContract extends BaseContract {
  connect(runner?: ContractRunner | null): MinMax256TestsContract;
  waitForDeployment(): Promise<this>;

  interface: MinMax256TestsContractInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getMaxResult: TypedContractMethod<[], [bigint], "view">;

  getMinResult: TypedContractMethod<[], [bigint], "view">;

  maxTest: TypedContractMethod<
    [a: BigNumberish, b: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  minTest: TypedContractMethod<
    [a: BigNumberish, b: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getMaxResult"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getMinResult"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "maxTest"
  ): TypedContractMethod<
    [a: BigNumberish, b: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "minTest"
  ): TypedContractMethod<
    [a: BigNumberish, b: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  filters: {};
}
