/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../../common";

export type CtUint256Struct = {
  ciphertextHigh: BigNumberish;
  ciphertextLow: BigNumberish;
};

export type CtUint256StructOutput = [
  ciphertextHigh: bigint,
  ciphertextLow: bigint
] & { ciphertextHigh: bigint; ciphertextLow: bigint };

export type ItUint256Struct = {
  ciphertext: CtUint256Struct;
  signature: BytesLike;
};

export type ItUint256StructOutput = [
  ciphertext: CtUint256StructOutput,
  signature: string
] & { ciphertext: CtUint256StructOutput; signature: string };

export interface MpcOperationsTestContractInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "add256"
      | "and256"
      | "div256"
      | "eq256"
      | "gt256"
      | "lt256"
      | "max256"
      | "min256"
      | "mul256"
      | "or256"
      | "rem256"
      | "shl256"
      | "shr256"
      | "sub256"
      | "xor256"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "OperationPerformed" | "ValueOffBoarded"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "add256",
    values: [ItUint256Struct, ItUint256Struct, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "and256",
    values: [ItUint256Struct, ItUint256Struct, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "div256",
    values: [ItUint256Struct, ItUint256Struct, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "eq256",
    values: [ItUint256Struct, ItUint256Struct, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "gt256",
    values: [ItUint256Struct, ItUint256Struct, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lt256",
    values: [ItUint256Struct, ItUint256Struct, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "max256",
    values: [ItUint256Struct, ItUint256Struct, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "min256",
    values: [ItUint256Struct, ItUint256Struct, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "mul256",
    values: [ItUint256Struct, ItUint256Struct, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "or256",
    values: [ItUint256Struct, ItUint256Struct, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "rem256",
    values: [ItUint256Struct, ItUint256Struct, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "shl256",
    values: [ItUint256Struct, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "shr256",
    values: [ItUint256Struct, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "sub256",
    values: [ItUint256Struct, ItUint256Struct, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "xor256",
    values: [ItUint256Struct, ItUint256Struct, AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "add256", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "and256", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "div256", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "eq256", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "gt256", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "lt256", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "max256", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "min256", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "mul256", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "or256", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "rem256", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "shl256", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "shr256", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "sub256", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "xor256", data: BytesLike): Result;
}

export namespace OperationPerformedEvent {
  export type InputTuple = [operation: string, user: AddressLike];
  export type OutputTuple = [operation: string, user: string];
  export interface OutputObject {
    operation: string;
    user: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ValueOffBoardedEvent {
  export type InputTuple = [user: AddressLike, result: CtUint256Struct];
  export type OutputTuple = [user: string, result: CtUint256StructOutput];
  export interface OutputObject {
    user: string;
    result: CtUint256StructOutput;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MpcOperationsTestContract extends BaseContract {
  connect(runner?: ContractRunner | null): MpcOperationsTestContract;
  waitForDeployment(): Promise<this>;

  interface: MpcOperationsTestContractInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  add256: TypedContractMethod<
    [a: ItUint256Struct, b: ItUint256Struct, user: AddressLike],
    [CtUint256StructOutput],
    "nonpayable"
  >;

  and256: TypedContractMethod<
    [a: ItUint256Struct, b: ItUint256Struct, user: AddressLike],
    [CtUint256StructOutput],
    "nonpayable"
  >;

  div256: TypedContractMethod<
    [a: ItUint256Struct, b: ItUint256Struct, user: AddressLike],
    [CtUint256StructOutput],
    "nonpayable"
  >;

  eq256: TypedContractMethod<
    [a: ItUint256Struct, b: ItUint256Struct, user: AddressLike],
    [CtUint256StructOutput],
    "nonpayable"
  >;

  gt256: TypedContractMethod<
    [a: ItUint256Struct, b: ItUint256Struct, user: AddressLike],
    [CtUint256StructOutput],
    "nonpayable"
  >;

  lt256: TypedContractMethod<
    [a: ItUint256Struct, b: ItUint256Struct, user: AddressLike],
    [CtUint256StructOutput],
    "nonpayable"
  >;

  max256: TypedContractMethod<
    [a: ItUint256Struct, b: ItUint256Struct, user: AddressLike],
    [CtUint256StructOutput],
    "nonpayable"
  >;

  min256: TypedContractMethod<
    [a: ItUint256Struct, b: ItUint256Struct, user: AddressLike],
    [CtUint256StructOutput],
    "nonpayable"
  >;

  mul256: TypedContractMethod<
    [a: ItUint256Struct, b: ItUint256Struct, user: AddressLike],
    [CtUint256StructOutput],
    "nonpayable"
  >;

  or256: TypedContractMethod<
    [a: ItUint256Struct, b: ItUint256Struct, user: AddressLike],
    [CtUint256StructOutput],
    "nonpayable"
  >;

  rem256: TypedContractMethod<
    [a: ItUint256Struct, b: ItUint256Struct, user: AddressLike],
    [CtUint256StructOutput],
    "nonpayable"
  >;

  shl256: TypedContractMethod<
    [a: ItUint256Struct, bits: BigNumberish, user: AddressLike],
    [CtUint256StructOutput],
    "nonpayable"
  >;

  shr256: TypedContractMethod<
    [a: ItUint256Struct, bits: BigNumberish, user: AddressLike],
    [CtUint256StructOutput],
    "nonpayable"
  >;

  sub256: TypedContractMethod<
    [a: ItUint256Struct, b: ItUint256Struct, user: AddressLike],
    [CtUint256StructOutput],
    "nonpayable"
  >;

  xor256: TypedContractMethod<
    [a: ItUint256Struct, b: ItUint256Struct, user: AddressLike],
    [CtUint256StructOutput],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "add256"
  ): TypedContractMethod<
    [a: ItUint256Struct, b: ItUint256Struct, user: AddressLike],
    [CtUint256StructOutput],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "and256"
  ): TypedContractMethod<
    [a: ItUint256Struct, b: ItUint256Struct, user: AddressLike],
    [CtUint256StructOutput],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "div256"
  ): TypedContractMethod<
    [a: ItUint256Struct, b: ItUint256Struct, user: AddressLike],
    [CtUint256StructOutput],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "eq256"
  ): TypedContractMethod<
    [a: ItUint256Struct, b: ItUint256Struct, user: AddressLike],
    [CtUint256StructOutput],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "gt256"
  ): TypedContractMethod<
    [a: ItUint256Struct, b: ItUint256Struct, user: AddressLike],
    [CtUint256StructOutput],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "lt256"
  ): TypedContractMethod<
    [a: ItUint256Struct, b: ItUint256Struct, user: AddressLike],
    [CtUint256StructOutput],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "max256"
  ): TypedContractMethod<
    [a: ItUint256Struct, b: ItUint256Struct, user: AddressLike],
    [CtUint256StructOutput],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "min256"
  ): TypedContractMethod<
    [a: ItUint256Struct, b: ItUint256Struct, user: AddressLike],
    [CtUint256StructOutput],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "mul256"
  ): TypedContractMethod<
    [a: ItUint256Struct, b: ItUint256Struct, user: AddressLike],
    [CtUint256StructOutput],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "or256"
  ): TypedContractMethod<
    [a: ItUint256Struct, b: ItUint256Struct, user: AddressLike],
    [CtUint256StructOutput],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "rem256"
  ): TypedContractMethod<
    [a: ItUint256Struct, b: ItUint256Struct, user: AddressLike],
    [CtUint256StructOutput],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "shl256"
  ): TypedContractMethod<
    [a: ItUint256Struct, bits: BigNumberish, user: AddressLike],
    [CtUint256StructOutput],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "shr256"
  ): TypedContractMethod<
    [a: ItUint256Struct, bits: BigNumberish, user: AddressLike],
    [CtUint256StructOutput],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "sub256"
  ): TypedContractMethod<
    [a: ItUint256Struct, b: ItUint256Struct, user: AddressLike],
    [CtUint256StructOutput],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "xor256"
  ): TypedContractMethod<
    [a: ItUint256Struct, b: ItUint256Struct, user: AddressLike],
    [CtUint256StructOutput],
    "nonpayable"
  >;

  getEvent(
    key: "OperationPerformed"
  ): TypedContractEvent<
    OperationPerformedEvent.InputTuple,
    OperationPerformedEvent.OutputTuple,
    OperationPerformedEvent.OutputObject
  >;
  getEvent(
    key: "ValueOffBoarded"
  ): TypedContractEvent<
    ValueOffBoardedEvent.InputTuple,
    ValueOffBoardedEvent.OutputTuple,
    ValueOffBoardedEvent.OutputObject
  >;

  filters: {
    "OperationPerformed(string,address)": TypedContractEvent<
      OperationPerformedEvent.InputTuple,
      OperationPerformedEvent.OutputTuple,
      OperationPerformedEvent.OutputObject
    >;
    OperationPerformed: TypedContractEvent<
      OperationPerformedEvent.InputTuple,
      OperationPerformedEvent.OutputTuple,
      OperationPerformedEvent.OutputObject
    >;

    "ValueOffBoarded(address,tuple)": TypedContractEvent<
      ValueOffBoardedEvent.InputTuple,
      ValueOffBoardedEvent.OutputTuple,
      ValueOffBoardedEvent.OutputObject
    >;
    ValueOffBoarded: TypedContractEvent<
      ValueOffBoardedEvent.InputTuple,
      ValueOffBoardedEvent.OutputTuple,
      ValueOffBoardedEvent.OutputObject
    >;
  };
}
