/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../../common";

export type ItUint128Struct = {
  ciphertext: BigNumberish;
  signature: BytesLike;
};

export type ItUint128StructOutput = [ciphertext: bigint, signature: string] & {
  ciphertext: bigint;
  signature: string;
};

export interface MpcOperations128TestContractInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "add128"
      | "and128"
      | "div128"
      | "max128"
      | "min128"
      | "mul128"
      | "or128"
      | "rem128"
      | "shl128"
      | "shr128"
      | "sub128"
      | "xor128"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "OperationPerformed" | "ValueOffBoarded128"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "add128",
    values: [ItUint128Struct, ItUint128Struct, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "and128",
    values: [ItUint128Struct, ItUint128Struct, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "div128",
    values: [ItUint128Struct, ItUint128Struct, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "max128",
    values: [ItUint128Struct, ItUint128Struct, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "min128",
    values: [ItUint128Struct, ItUint128Struct, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "mul128",
    values: [ItUint128Struct, ItUint128Struct, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "or128",
    values: [ItUint128Struct, ItUint128Struct, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "rem128",
    values: [ItUint128Struct, ItUint128Struct, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "shl128",
    values: [ItUint128Struct, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "shr128",
    values: [ItUint128Struct, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "sub128",
    values: [ItUint128Struct, ItUint128Struct, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "xor128",
    values: [ItUint128Struct, ItUint128Struct, AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "add128", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "and128", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "div128", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "max128", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "min128", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "mul128", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "or128", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "rem128", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "shl128", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "shr128", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "sub128", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "xor128", data: BytesLike): Result;
}

export namespace OperationPerformedEvent {
  export type InputTuple = [operation: string, user: AddressLike];
  export type OutputTuple = [operation: string, user: string];
  export interface OutputObject {
    operation: string;
    user: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ValueOffBoarded128Event {
  export type InputTuple = [user: AddressLike, result: BigNumberish];
  export type OutputTuple = [user: string, result: bigint];
  export interface OutputObject {
    user: string;
    result: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MpcOperations128TestContract extends BaseContract {
  connect(runner?: ContractRunner | null): MpcOperations128TestContract;
  waitForDeployment(): Promise<this>;

  interface: MpcOperations128TestContractInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  add128: TypedContractMethod<
    [a: ItUint128Struct, b: ItUint128Struct, user: AddressLike],
    [bigint],
    "nonpayable"
  >;

  and128: TypedContractMethod<
    [a: ItUint128Struct, b: ItUint128Struct, user: AddressLike],
    [bigint],
    "nonpayable"
  >;

  div128: TypedContractMethod<
    [a: ItUint128Struct, b: ItUint128Struct, user: AddressLike],
    [bigint],
    "nonpayable"
  >;

  max128: TypedContractMethod<
    [a: ItUint128Struct, b: ItUint128Struct, user: AddressLike],
    [bigint],
    "nonpayable"
  >;

  min128: TypedContractMethod<
    [a: ItUint128Struct, b: ItUint128Struct, user: AddressLike],
    [bigint],
    "nonpayable"
  >;

  mul128: TypedContractMethod<
    [a: ItUint128Struct, b: ItUint128Struct, user: AddressLike],
    [bigint],
    "nonpayable"
  >;

  or128: TypedContractMethod<
    [a: ItUint128Struct, b: ItUint128Struct, user: AddressLike],
    [bigint],
    "nonpayable"
  >;

  rem128: TypedContractMethod<
    [a: ItUint128Struct, b: ItUint128Struct, user: AddressLike],
    [bigint],
    "nonpayable"
  >;

  shl128: TypedContractMethod<
    [a: ItUint128Struct, bits: BigNumberish, user: AddressLike],
    [bigint],
    "nonpayable"
  >;

  shr128: TypedContractMethod<
    [a: ItUint128Struct, bits: BigNumberish, user: AddressLike],
    [bigint],
    "nonpayable"
  >;

  sub128: TypedContractMethod<
    [a: ItUint128Struct, b: ItUint128Struct, user: AddressLike],
    [bigint],
    "nonpayable"
  >;

  xor128: TypedContractMethod<
    [a: ItUint128Struct, b: ItUint128Struct, user: AddressLike],
    [bigint],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "add128"
  ): TypedContractMethod<
    [a: ItUint128Struct, b: ItUint128Struct, user: AddressLike],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "and128"
  ): TypedContractMethod<
    [a: ItUint128Struct, b: ItUint128Struct, user: AddressLike],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "div128"
  ): TypedContractMethod<
    [a: ItUint128Struct, b: ItUint128Struct, user: AddressLike],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "max128"
  ): TypedContractMethod<
    [a: ItUint128Struct, b: ItUint128Struct, user: AddressLike],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "min128"
  ): TypedContractMethod<
    [a: ItUint128Struct, b: ItUint128Struct, user: AddressLike],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "mul128"
  ): TypedContractMethod<
    [a: ItUint128Struct, b: ItUint128Struct, user: AddressLike],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "or128"
  ): TypedContractMethod<
    [a: ItUint128Struct, b: ItUint128Struct, user: AddressLike],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "rem128"
  ): TypedContractMethod<
    [a: ItUint128Struct, b: ItUint128Struct, user: AddressLike],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "shl128"
  ): TypedContractMethod<
    [a: ItUint128Struct, bits: BigNumberish, user: AddressLike],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "shr128"
  ): TypedContractMethod<
    [a: ItUint128Struct, bits: BigNumberish, user: AddressLike],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "sub128"
  ): TypedContractMethod<
    [a: ItUint128Struct, b: ItUint128Struct, user: AddressLike],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "xor128"
  ): TypedContractMethod<
    [a: ItUint128Struct, b: ItUint128Struct, user: AddressLike],
    [bigint],
    "nonpayable"
  >;

  getEvent(
    key: "OperationPerformed"
  ): TypedContractEvent<
    OperationPerformedEvent.InputTuple,
    OperationPerformedEvent.OutputTuple,
    OperationPerformedEvent.OutputObject
  >;
  getEvent(
    key: "ValueOffBoarded128"
  ): TypedContractEvent<
    ValueOffBoarded128Event.InputTuple,
    ValueOffBoarded128Event.OutputTuple,
    ValueOffBoarded128Event.OutputObject
  >;

  filters: {
    "OperationPerformed(string,address)": TypedContractEvent<
      OperationPerformedEvent.InputTuple,
      OperationPerformedEvent.OutputTuple,
      OperationPerformedEvent.OutputObject
    >;
    OperationPerformed: TypedContractEvent<
      OperationPerformedEvent.InputTuple,
      OperationPerformedEvent.OutputTuple,
      OperationPerformedEvent.OutputObject
    >;

    "ValueOffBoarded128(address,uint256)": TypedContractEvent<
      ValueOffBoarded128Event.InputTuple,
      ValueOffBoarded128Event.OutputTuple,
      ValueOffBoarded128Event.OutputObject
    >;
    ValueOffBoarded128: TypedContractEvent<
      ValueOffBoarded128Event.InputTuple,
      ValueOffBoarded128Event.OutputTuple,
      ValueOffBoarded128Event.OutputObject
    >;
  };
}
