/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../../common";

export interface Shift128TestsContractInterface extends Interface {
  getFunction(
    nameOrSignature: "getShlResult" | "getShrResult" | "shlTest" | "shrTest"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getShlResult",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getShrResult",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "shlTest",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "shrTest",
    values: [BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "getShlResult",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getShrResult",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "shlTest", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "shrTest", data: BytesLike): Result;
}

export interface Shift128TestsContract extends BaseContract {
  connect(runner?: ContractRunner | null): Shift128TestsContract;
  waitForDeployment(): Promise<this>;

  interface: Shift128TestsContractInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getShlResult: TypedContractMethod<[], [bigint], "view">;

  getShrResult: TypedContractMethod<[], [bigint], "view">;

  shlTest: TypedContractMethod<
    [a: BigNumberish, shift: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  shrTest: TypedContractMethod<
    [a: BigNumberish, shift: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getShlResult"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getShrResult"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "shlTest"
  ): TypedContractMethod<
    [a: BigNumberish, shift: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "shrTest"
  ): TypedContractMethod<
    [a: BigNumberish, shift: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  filters: {};
}
