/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../../common";

export type CtUint256Struct = {
  ciphertextHigh: BigNumberish;
  ciphertextLow: BigNumberish;
};

export type CtUint256StructOutput = [
  ciphertextHigh: bigint,
  ciphertextLow: bigint
] & { ciphertextHigh: bigint; ciphertextLow: bigint };

export type ItUint256Struct = {
  ciphertext: CtUint256Struct;
  signature: BytesLike;
};

export type ItUint256StructOutput = [
  ciphertext: CtUint256StructOutput,
  signature: string
] & { ciphertext: CtUint256StructOutput; signature: string };

export interface ValidateCiphertext256TestsContractInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getStoredEncryptedValue"
      | "getStoredValue"
      | "getValidationResult"
      | "validateAndIncrement"
      | "validateAndStore"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getStoredEncryptedValue",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getStoredValue",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getValidationResult",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "validateAndIncrement",
    values: [ItUint256Struct]
  ): string;
  encodeFunctionData(
    functionFragment: "validateAndStore",
    values: [ItUint256Struct]
  ): string;

  decodeFunctionResult(
    functionFragment: "getStoredEncryptedValue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getStoredValue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getValidationResult",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "validateAndIncrement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "validateAndStore",
    data: BytesLike
  ): Result;
}

export interface ValidateCiphertext256TestsContract extends BaseContract {
  connect(runner?: ContractRunner | null): ValidateCiphertext256TestsContract;
  waitForDeployment(): Promise<this>;

  interface: ValidateCiphertext256TestsContractInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getStoredEncryptedValue: TypedContractMethod<
    [],
    [CtUint256StructOutput],
    "view"
  >;

  getStoredValue: TypedContractMethod<[], [bigint], "view">;

  getValidationResult: TypedContractMethod<[], [boolean], "view">;

  validateAndIncrement: TypedContractMethod<
    [input: ItUint256Struct],
    [bigint],
    "nonpayable"
  >;

  validateAndStore: TypedContractMethod<
    [input: ItUint256Struct],
    [bigint],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getStoredEncryptedValue"
  ): TypedContractMethod<[], [CtUint256StructOutput], "view">;
  getFunction(
    nameOrSignature: "getStoredValue"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getValidationResult"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "validateAndIncrement"
  ): TypedContractMethod<[input: ItUint256Struct], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "validateAndStore"
  ): TypedContractMethod<[input: ItUint256Struct], [bigint], "nonpayable">;

  filters: {};
}
