/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../../common";

export type ItUint8Struct = { ciphertext: BigNumberish; signature: BytesLike };

export type ItUint8StructOutput = [ciphertext: bigint, signature: string] & {
  ciphertext: bigint;
  signature: string;
};

export interface ValidateCiphertextTestsContractInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getStoredEncryptedValue"
      | "getStoredValue"
      | "getValidationResult"
      | "validateAndAdd"
      | "validateAndReturn"
      | "validateAndStore"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "ValueOffBoarded" | "ValueValidated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "getStoredEncryptedValue",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getStoredValue",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getValidationResult",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "validateAndAdd",
    values: [ItUint8Struct, ItUint8Struct]
  ): string;
  encodeFunctionData(
    functionFragment: "validateAndReturn",
    values: [ItUint8Struct]
  ): string;
  encodeFunctionData(
    functionFragment: "validateAndStore",
    values: [ItUint8Struct]
  ): string;

  decodeFunctionResult(
    functionFragment: "getStoredEncryptedValue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getStoredValue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getValidationResult",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "validateAndAdd",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "validateAndReturn",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "validateAndStore",
    data: BytesLike
  ): Result;
}

export namespace ValueOffBoardedEvent {
  export type InputTuple = [user: AddressLike, result: BigNumberish];
  export type OutputTuple = [user: string, result: bigint];
  export interface OutputObject {
    user: string;
    result: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ValueValidatedEvent {
  export type InputTuple = [user: AddressLike, operation: string];
  export type OutputTuple = [user: string, operation: string];
  export interface OutputObject {
    user: string;
    operation: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ValidateCiphertextTestsContract extends BaseContract {
  connect(runner?: ContractRunner | null): ValidateCiphertextTestsContract;
  waitForDeployment(): Promise<this>;

  interface: ValidateCiphertextTestsContractInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getStoredEncryptedValue: TypedContractMethod<[], [bigint], "view">;

  getStoredValue: TypedContractMethod<[], [bigint], "view">;

  getValidationResult: TypedContractMethod<[], [boolean], "view">;

  validateAndAdd: TypedContractMethod<
    [a: ItUint8Struct, b: ItUint8Struct],
    [bigint],
    "nonpayable"
  >;

  validateAndReturn: TypedContractMethod<
    [input: ItUint8Struct],
    [bigint],
    "nonpayable"
  >;

  validateAndStore: TypedContractMethod<
    [input: ItUint8Struct],
    [bigint],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getStoredEncryptedValue"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getStoredValue"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getValidationResult"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "validateAndAdd"
  ): TypedContractMethod<
    [a: ItUint8Struct, b: ItUint8Struct],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "validateAndReturn"
  ): TypedContractMethod<[input: ItUint8Struct], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "validateAndStore"
  ): TypedContractMethod<[input: ItUint8Struct], [bigint], "nonpayable">;

  getEvent(
    key: "ValueOffBoarded"
  ): TypedContractEvent<
    ValueOffBoardedEvent.InputTuple,
    ValueOffBoardedEvent.OutputTuple,
    ValueOffBoardedEvent.OutputObject
  >;
  getEvent(
    key: "ValueValidated"
  ): TypedContractEvent<
    ValueValidatedEvent.InputTuple,
    ValueValidatedEvent.OutputTuple,
    ValueValidatedEvent.OutputObject
  >;

  filters: {
    "ValueOffBoarded(address,uint256)": TypedContractEvent<
      ValueOffBoardedEvent.InputTuple,
      ValueOffBoardedEvent.OutputTuple,
      ValueOffBoardedEvent.OutputObject
    >;
    ValueOffBoarded: TypedContractEvent<
      ValueOffBoardedEvent.InputTuple,
      ValueOffBoardedEvent.OutputTuple,
      ValueOffBoardedEvent.OutputObject
    >;

    "ValueValidated(address,string)": TypedContractEvent<
      ValueValidatedEvent.InputTuple,
      ValueValidatedEvent.OutputTuple,
      ValueValidatedEvent.OutputObject
    >;
    ValueValidated: TypedContractEvent<
      ValueValidatedEvent.InputTuple,
      ValueValidatedEvent.OutputTuple,
      ValueValidatedEvent.OutputObject
    >;
  };
}
