/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IPodERC20,
  IPodERC20Interface,
} from "../../../../../contracts/pod/token/perc20/IPodERC20";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "owner",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "spender",
        type: "address",
      },
      {
        components: [
          {
            internalType: "ctUint128",
            name: "ciphertextHigh",
            type: "uint256",
          },
          {
            internalType: "ctUint128",
            name: "ciphertextLow",
            type: "uint256",
          },
        ],
        indexed: false,
        internalType: "struct ctUint256",
        name: "ownerValue",
        type: "tuple",
      },
      {
        components: [
          {
            internalType: "ctUint128",
            name: "ciphertextHigh",
            type: "uint256",
          },
          {
            internalType: "ctUint128",
            name: "ciphertextLow",
            type: "uint256",
          },
        ],
        indexed: false,
        internalType: "struct ctUint256",
        name: "spenderValue",
        type: "tuple",
      },
    ],
    name: "Approval",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        components: [
          {
            internalType: "ctUint128",
            name: "ciphertextHigh",
            type: "uint256",
          },
          {
            internalType: "ctUint128",
            name: "ciphertextLow",
            type: "uint256",
          },
        ],
        indexed: false,
        internalType: "struct ctUint256",
        name: "amount",
        type: "tuple",
      },
    ],
    name: "BalanceSynced",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "requestId",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "bytes",
        name: "callbackData",
        type: "bytes",
      },
    ],
    name: "RequestCallbackFailed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "requestId",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "enum IPodERC20.RequestStatus",
        name: "status",
        type: "uint8",
      },
    ],
    name: "RequestStatusUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        components: [
          {
            internalType: "ctUint128",
            name: "ciphertextHigh",
            type: "uint256",
          },
          {
            internalType: "ctUint128",
            name: "ciphertextLow",
            type: "uint256",
          },
        ],
        indexed: false,
        internalType: "struct ctUint256",
        name: "senderValue",
        type: "tuple",
      },
      {
        components: [
          {
            internalType: "ctUint128",
            name: "ciphertextHigh",
            type: "uint256",
          },
          {
            internalType: "ctUint128",
            name: "ciphertextLow",
            type: "uint256",
          },
        ],
        indexed: false,
        internalType: "struct ctUint256",
        name: "receiverValue",
        type: "tuple",
      },
    ],
    name: "Transfer",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        indexed: false,
        internalType: "bytes",
        name: "errorMsg",
        type: "bytes",
      },
    ],
    name: "TransferFailed",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "owner",
        type: "address",
      },
      {
        internalType: "address",
        name: "spender",
        type: "address",
      },
    ],
    name: "allowance",
    outputs: [
      {
        components: [
          {
            components: [
              {
                internalType: "ctUint128",
                name: "ciphertextHigh",
                type: "uint256",
              },
              {
                internalType: "ctUint128",
                name: "ciphertextLow",
                type: "uint256",
              },
            ],
            internalType: "struct ctUint256",
            name: "ownerCiphertext",
            type: "tuple",
          },
          {
            components: [
              {
                internalType: "ctUint128",
                name: "ciphertextHigh",
                type: "uint256",
              },
              {
                internalType: "ctUint128",
                name: "ciphertextLow",
                type: "uint256",
              },
            ],
            internalType: "struct ctUint256",
            name: "spenderCiphertext",
            type: "tuple",
          },
        ],
        internalType: "struct IPodERC20.Allowance",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "owner",
        type: "address",
      },
      {
        internalType: "address",
        name: "spender",
        type: "address",
      },
    ],
    name: "allowanceWithStatus",
    outputs: [
      {
        components: [
          {
            components: [
              {
                internalType: "ctUint128",
                name: "ciphertextHigh",
                type: "uint256",
              },
              {
                internalType: "ctUint128",
                name: "ciphertextLow",
                type: "uint256",
              },
            ],
            internalType: "struct ctUint256",
            name: "ownerCiphertext",
            type: "tuple",
          },
          {
            components: [
              {
                internalType: "ctUint128",
                name: "ciphertextHigh",
                type: "uint256",
              },
              {
                internalType: "ctUint128",
                name: "ciphertextLow",
                type: "uint256",
              },
            ],
            internalType: "struct ctUint256",
            name: "spenderCiphertext",
            type: "tuple",
          },
        ],
        internalType: "struct IPodERC20.Allowance",
        name: "",
        type: "tuple",
      },
      {
        internalType: "bool",
        name: "pending",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "spender",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "callbackFeeLocalWei",
        type: "uint256",
      },
    ],
    name: "approve",
    outputs: [
      {
        internalType: "bytes32",
        name: "requestId",
        type: "bytes32",
      },
    ],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "spender",
        type: "address",
      },
      {
        components: [
          {
            components: [
              {
                internalType: "ctUint128",
                name: "ciphertextHigh",
                type: "uint256",
              },
              {
                internalType: "ctUint128",
                name: "ciphertextLow",
                type: "uint256",
              },
            ],
            internalType: "struct ctUint256",
            name: "ciphertext",
            type: "tuple",
          },
          {
            internalType: "bytes",
            name: "signature",
            type: "bytes",
          },
        ],
        internalType: "struct itUint256",
        name: "value",
        type: "tuple",
      },
    ],
    name: "approve",
    outputs: [
      {
        internalType: "bytes32",
        name: "requestId",
        type: "bytes32",
      },
    ],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "spender",
        type: "address",
      },
      {
        components: [
          {
            components: [
              {
                internalType: "ctUint128",
                name: "ciphertextHigh",
                type: "uint256",
              },
              {
                internalType: "ctUint128",
                name: "ciphertextLow",
                type: "uint256",
              },
            ],
            internalType: "struct ctUint256",
            name: "ciphertext",
            type: "tuple",
          },
          {
            internalType: "bytes",
            name: "signature",
            type: "bytes",
          },
        ],
        internalType: "struct itUint256",
        name: "value",
        type: "tuple",
      },
      {
        internalType: "uint256",
        name: "callbackFeeLocalWei",
        type: "uint256",
      },
    ],
    name: "approve",
    outputs: [
      {
        internalType: "bytes32",
        name: "requestId",
        type: "bytes32",
      },
    ],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "balanceOf",
    outputs: [
      {
        components: [
          {
            internalType: "ctUint128",
            name: "ciphertextHigh",
            type: "uint256",
          },
          {
            internalType: "ctUint128",
            name: "ciphertextLow",
            type: "uint256",
          },
        ],
        internalType: "struct ctUint256",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "balanceOfWithStatus",
    outputs: [
      {
        components: [
          {
            internalType: "ctUint128",
            name: "ciphertextHigh",
            type: "uint256",
          },
          {
            internalType: "ctUint128",
            name: "ciphertextLow",
            type: "uint256",
          },
        ],
        internalType: "struct ctUint256",
        name: "",
        type: "tuple",
      },
      {
        internalType: "bool",
        name: "pending",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            components: [
              {
                internalType: "ctUint128",
                name: "ciphertextHigh",
                type: "uint256",
              },
              {
                internalType: "ctUint128",
                name: "ciphertextLow",
                type: "uint256",
              },
            ],
            internalType: "struct ctUint256",
            name: "ciphertext",
            type: "tuple",
          },
          {
            internalType: "bytes",
            name: "signature",
            type: "bytes",
          },
        ],
        internalType: "struct itUint256",
        name: "amount",
        type: "tuple",
      },
      {
        internalType: "uint256",
        name: "callbackFeeLocalWei",
        type: "uint256",
      },
    ],
    name: "burn",
    outputs: [
      {
        internalType: "bytes32",
        name: "requestId",
        type: "bytes32",
      },
    ],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "callbackFeeLocalWei",
        type: "uint256",
      },
    ],
    name: "burn",
    outputs: [
      {
        internalType: "bytes32",
        name: "requestId",
        type: "bytes32",
      },
    ],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [],
    name: "estimateFee",
    outputs: [
      {
        internalType: "uint256",
        name: "totalFeeWei",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "targetFeeWei",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "callbackFeeWei",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "callbackFeeLocalWei",
        type: "uint256",
      },
    ],
    name: "mint",
    outputs: [
      {
        internalType: "bytes32",
        name: "requestId",
        type: "bytes32",
      },
    ],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        components: [
          {
            components: [
              {
                internalType: "ctUint128",
                name: "ciphertextHigh",
                type: "uint256",
              },
              {
                internalType: "ctUint128",
                name: "ciphertextLow",
                type: "uint256",
              },
            ],
            internalType: "struct ctUint256",
            name: "ciphertext",
            type: "tuple",
          },
          {
            internalType: "bytes",
            name: "signature",
            type: "bytes",
          },
        ],
        internalType: "struct itUint256",
        name: "amount",
        type: "tuple",
      },
      {
        internalType: "uint256",
        name: "callbackFeeLocalWei",
        type: "uint256",
      },
    ],
    name: "mint",
    outputs: [
      {
        internalType: "bytes32",
        name: "requestId",
        type: "bytes32",
      },
    ],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "requestId",
        type: "bytes32",
      },
    ],
    name: "requests",
    outputs: [
      {
        internalType: "enum IPodERC20.RequestStatus",
        name: "",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address[]",
        name: "accounts",
        type: "address[]",
      },
      {
        internalType: "uint256",
        name: "callbackFeeLocalWei",
        type: "uint256",
      },
    ],
    name: "syncBalances",
    outputs: [
      {
        internalType: "bytes32",
        name: "requestId",
        type: "bytes32",
      },
    ],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [],
    name: "totalSupply",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "callbackFeeLocalWei",
        type: "uint256",
      },
    ],
    name: "transfer",
    outputs: [
      {
        internalType: "bytes32",
        name: "requestId",
        type: "bytes32",
      },
    ],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        components: [
          {
            components: [
              {
                internalType: "ctUint128",
                name: "ciphertextHigh",
                type: "uint256",
              },
              {
                internalType: "ctUint128",
                name: "ciphertextLow",
                type: "uint256",
              },
            ],
            internalType: "struct ctUint256",
            name: "ciphertext",
            type: "tuple",
          },
          {
            internalType: "bytes",
            name: "signature",
            type: "bytes",
          },
        ],
        internalType: "struct itUint256",
        name: "value",
        type: "tuple",
      },
    ],
    name: "transfer",
    outputs: [
      {
        internalType: "bytes32",
        name: "requestId",
        type: "bytes32",
      },
    ],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        components: [
          {
            components: [
              {
                internalType: "ctUint128",
                name: "ciphertextHigh",
                type: "uint256",
              },
              {
                internalType: "ctUint128",
                name: "ciphertextLow",
                type: "uint256",
              },
            ],
            internalType: "struct ctUint256",
            name: "ciphertext",
            type: "tuple",
          },
          {
            internalType: "bytes",
            name: "signature",
            type: "bytes",
          },
        ],
        internalType: "struct itUint256",
        name: "value",
        type: "tuple",
      },
      {
        internalType: "uint256",
        name: "callbackFeeLocalWei",
        type: "uint256",
      },
    ],
    name: "transfer",
    outputs: [
      {
        internalType: "bytes32",
        name: "requestId",
        type: "bytes32",
      },
    ],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        components: [
          {
            components: [
              {
                internalType: "ctUint128",
                name: "ciphertextHigh",
                type: "uint256",
              },
              {
                internalType: "ctUint128",
                name: "ciphertextLow",
                type: "uint256",
              },
            ],
            internalType: "struct ctUint256",
            name: "ciphertext",
            type: "tuple",
          },
          {
            internalType: "bytes",
            name: "signature",
            type: "bytes",
          },
        ],
        internalType: "struct itUint256",
        name: "amount",
        type: "tuple",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
      {
        internalType: "uint256",
        name: "callbackFeeLocalWei",
        type: "uint256",
      },
    ],
    name: "transferAndCall",
    outputs: [
      {
        internalType: "bytes32",
        name: "requestId",
        type: "bytes32",
      },
    ],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        components: [
          {
            components: [
              {
                internalType: "ctUint128",
                name: "ciphertextHigh",
                type: "uint256",
              },
              {
                internalType: "ctUint128",
                name: "ciphertextLow",
                type: "uint256",
              },
            ],
            internalType: "struct ctUint256",
            name: "ciphertext",
            type: "tuple",
          },
          {
            internalType: "bytes",
            name: "signature",
            type: "bytes",
          },
        ],
        internalType: "struct itUint256",
        name: "value",
        type: "tuple",
      },
    ],
    name: "transferFrom",
    outputs: [
      {
        internalType: "bytes32",
        name: "requestId",
        type: "bytes32",
      },
    ],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        components: [
          {
            components: [
              {
                internalType: "ctUint128",
                name: "ciphertextHigh",
                type: "uint256",
              },
              {
                internalType: "ctUint128",
                name: "ciphertextLow",
                type: "uint256",
              },
            ],
            internalType: "struct ctUint256",
            name: "ciphertext",
            type: "tuple",
          },
          {
            internalType: "bytes",
            name: "signature",
            type: "bytes",
          },
        ],
        internalType: "struct itUint256",
        name: "value",
        type: "tuple",
      },
      {
        internalType: "uint256",
        name: "callbackFeeLocalWei",
        type: "uint256",
      },
    ],
    name: "transferFrom",
    outputs: [
      {
        internalType: "bytes32",
        name: "requestId",
        type: "bytes32",
      },
    ],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "callbackFeeLocalWei",
        type: "uint256",
      },
    ],
    name: "transferFrom",
    outputs: [
      {
        internalType: "bytes32",
        name: "requestId",
        type: "bytes32",
      },
    ],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
      {
        internalType: "uint256",
        name: "callbackFeeLocalWei",
        type: "uint256",
      },
    ],
    name: "transferFromAndCall",
    outputs: [
      {
        internalType: "bytes32",
        name: "requestId",
        type: "bytes32",
      },
    ],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        components: [
          {
            internalType: "uint256",
            name: "deadline",
            type: "uint256",
          },
          {
            internalType: "uint8",
            name: "v",
            type: "uint8",
          },
          {
            internalType: "bytes32",
            name: "r",
            type: "bytes32",
          },
          {
            internalType: "bytes32",
            name: "s",
            type: "bytes32",
          },
        ],
        internalType: "struct IPodERC20.PublicPermit",
        name: "permit",
        type: "tuple",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
      {
        internalType: "uint256",
        name: "callbackFeeLocalWei",
        type: "uint256",
      },
    ],
    name: "transferFromAndCallWithPermit",
    outputs: [
      {
        internalType: "bytes32",
        name: "requestId",
        type: "bytes32",
      },
    ],
    stateMutability: "payable",
    type: "function",
  },
] as const;

export class IPodERC20__factory {
  static readonly abi = _abi;
  static createInterface(): IPodERC20Interface {
    return new Interface(_abi) as IPodERC20Interface;
  }
  static connect(address: string, runner?: ContractRunner | null): IPodERC20 {
    return new Contract(address, _abi, runner) as unknown as IPodERC20;
  }
}
