/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { TransferWithAllowance64TestsContract } from "./TransferWithAllowance64TestsContract";
export type { TransferWithAllowanceTestsContract } from "./TransferWithAllowanceTestsContract";
