/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc7984 from "./erc7984";
export type { erc7984 };
import type * as perc20 from "./perc20";
export type { perc20 };
