/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { TransferTestsContract__factory } from "./TransferTestsContract__factory";
export { TransferWithAllowanceTestsContract__factory } from "./TransferWithAllowanceTestsContract__factory";
