/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IPodExecutor256,
  IPodExecutor256Interface,
} from "../../../../../../contracts/pod/mpc/coti-side/IPodExecutorOps.sol/IPodExecutor256";

const _abi = [
  {
    inputs: [
      {
        internalType: "gtUint256",
        name: "a",
        type: "uint256",
      },
      {
        internalType: "gtUint256",
        name: "b",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "cOwner",
        type: "address",
      },
    ],
    name: "add256",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "gtUint256",
        name: "a",
        type: "uint256",
      },
      {
        internalType: "gtUint256",
        name: "b",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "cOwner",
        type: "address",
      },
    ],
    name: "and256",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "gtUint256",
        name: "a",
        type: "uint256",
      },
      {
        internalType: "gtUint256",
        name: "b",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "cOwner",
        type: "address",
      },
    ],
    name: "eq256",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "gtUint256",
        name: "a",
        type: "uint256",
      },
      {
        internalType: "gtUint256",
        name: "b",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "cOwner",
        type: "address",
      },
    ],
    name: "ge256",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "gtUint256",
        name: "a",
        type: "uint256",
      },
      {
        internalType: "gtUint256",
        name: "b",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "cOwner",
        type: "address",
      },
    ],
    name: "gt256",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "gtUint256",
        name: "a",
        type: "uint256",
      },
      {
        internalType: "gtUint256",
        name: "b",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "cOwner",
        type: "address",
      },
    ],
    name: "le256",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "gtUint256",
        name: "a",
        type: "uint256",
      },
      {
        internalType: "gtUint256",
        name: "b",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "cOwner",
        type: "address",
      },
    ],
    name: "lt256",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "gtUint256",
        name: "a",
        type: "uint256",
      },
      {
        internalType: "gtUint256",
        name: "b",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "cOwner",
        type: "address",
      },
    ],
    name: "max256",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "gtUint256",
        name: "a",
        type: "uint256",
      },
      {
        internalType: "gtUint256",
        name: "b",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "cOwner",
        type: "address",
      },
    ],
    name: "min256",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "gtUint256",
        name: "a",
        type: "uint256",
      },
      {
        internalType: "gtUint256",
        name: "b",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "cOwner",
        type: "address",
      },
    ],
    name: "mul256",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "gtUint256",
        name: "a",
        type: "uint256",
      },
      {
        internalType: "gtUint256",
        name: "b",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "cOwner",
        type: "address",
      },
    ],
    name: "mulWrapping256",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "gtBool",
        name: "bit",
        type: "uint256",
      },
      {
        internalType: "gtUint256",
        name: "a",
        type: "uint256",
      },
      {
        internalType: "gtUint256",
        name: "b",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "cOwner",
        type: "address",
      },
    ],
    name: "mux256",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "gtUint256",
        name: "a",
        type: "uint256",
      },
      {
        internalType: "gtUint256",
        name: "b",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "cOwner",
        type: "address",
      },
    ],
    name: "ne256",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "gtUint256",
        name: "a",
        type: "uint256",
      },
      {
        internalType: "gtUint256",
        name: "b",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "cOwner",
        type: "address",
      },
    ],
    name: "or256",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "cOwner",
        type: "address",
      },
    ],
    name: "rand256",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint8",
        name: "numBits",
        type: "uint8",
      },
      {
        internalType: "address",
        name: "cOwner",
        type: "address",
      },
    ],
    name: "randBoundedBits256",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "gtUint256",
        name: "a",
        type: "uint256",
      },
      {
        internalType: "uint8",
        name: "s",
        type: "uint8",
      },
      {
        internalType: "address",
        name: "cOwner",
        type: "address",
      },
    ],
    name: "shl256",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "gtUint256",
        name: "a",
        type: "uint256",
      },
      {
        internalType: "uint8",
        name: "s",
        type: "uint8",
      },
      {
        internalType: "address",
        name: "cOwner",
        type: "address",
      },
    ],
    name: "shr256",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "gtUint256",
        name: "a",
        type: "uint256",
      },
      {
        internalType: "gtUint256",
        name: "b",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "cOwner",
        type: "address",
      },
    ],
    name: "sub256",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "gtUint256",
        name: "a",
        type: "uint256",
      },
      {
        internalType: "gtUint256",
        name: "b",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "cOwner",
        type: "address",
      },
    ],
    name: "xor256",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IPodExecutor256__factory {
  static readonly abi = _abi;
  static createInterface(): IPodExecutor256Interface {
    return new Interface(_abi) as IPodExecutor256Interface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IPodExecutor256 {
    return new Contract(address, _abi, runner) as unknown as IPodExecutor256;
  }
}
