/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IPodExecutor128,
  IPodExecutor128Interface,
} from "../../../../../../contracts/pod/mpc/coti-side/IPodExecutorOps.sol/IPodExecutor128";

const _abi = [
  {
    inputs: [
      {
        internalType: "gtUint128",
        name: "a",
        type: "uint256",
      },
      {
        internalType: "gtUint128",
        name: "b",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "cOwner",
        type: "address",
      },
    ],
    name: "add128",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "gtUint128",
        name: "a",
        type: "uint256",
      },
      {
        internalType: "gtUint128",
        name: "b",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "cOwner",
        type: "address",
      },
    ],
    name: "and128",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "gtUint128",
        name: "a",
        type: "uint256",
      },
      {
        internalType: "gtUint128",
        name: "b",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "cOwner",
        type: "address",
      },
    ],
    name: "eq128",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "gtUint128",
        name: "a",
        type: "uint256",
      },
      {
        internalType: "gtUint128",
        name: "b",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "cOwner",
        type: "address",
      },
    ],
    name: "ge128",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "gtUint128",
        name: "a",
        type: "uint256",
      },
      {
        internalType: "gtUint128",
        name: "b",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "cOwner",
        type: "address",
      },
    ],
    name: "gt128",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "gtUint128",
        name: "a",
        type: "uint256",
      },
      {
        internalType: "gtUint128",
        name: "b",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "cOwner",
        type: "address",
      },
    ],
    name: "le128",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "gtUint128",
        name: "a",
        type: "uint256",
      },
      {
        internalType: "gtUint128",
        name: "b",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "cOwner",
        type: "address",
      },
    ],
    name: "lt128",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "gtUint128",
        name: "a",
        type: "uint256",
      },
      {
        internalType: "gtUint128",
        name: "b",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "cOwner",
        type: "address",
      },
    ],
    name: "max128",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "gtUint128",
        name: "a",
        type: "uint256",
      },
      {
        internalType: "gtUint128",
        name: "b",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "cOwner",
        type: "address",
      },
    ],
    name: "min128",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "gtUint128",
        name: "a",
        type: "uint256",
      },
      {
        internalType: "gtUint128",
        name: "b",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "cOwner",
        type: "address",
      },
    ],
    name: "mul128",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "gtUint128",
        name: "a",
        type: "uint256",
      },
      {
        internalType: "gtUint128",
        name: "b",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "cOwner",
        type: "address",
      },
    ],
    name: "mulWrapping128",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "gtBool",
        name: "bit",
        type: "uint256",
      },
      {
        internalType: "gtUint128",
        name: "a",
        type: "uint256",
      },
      {
        internalType: "gtUint128",
        name: "b",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "cOwner",
        type: "address",
      },
    ],
    name: "mux128",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "gtUint128",
        name: "a",
        type: "uint256",
      },
      {
        internalType: "gtUint128",
        name: "b",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "cOwner",
        type: "address",
      },
    ],
    name: "ne128",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "gtUint128",
        name: "a",
        type: "uint256",
      },
      {
        internalType: "gtUint128",
        name: "b",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "cOwner",
        type: "address",
      },
    ],
    name: "or128",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "cOwner",
        type: "address",
      },
    ],
    name: "rand128",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint8",
        name: "numBits",
        type: "uint8",
      },
      {
        internalType: "address",
        name: "cOwner",
        type: "address",
      },
    ],
    name: "randBoundedBits128",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "gtUint128",
        name: "a",
        type: "uint256",
      },
      {
        internalType: "uint8",
        name: "s",
        type: "uint8",
      },
      {
        internalType: "address",
        name: "cOwner",
        type: "address",
      },
    ],
    name: "shl128",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "gtUint128",
        name: "a",
        type: "uint256",
      },
      {
        internalType: "uint8",
        name: "s",
        type: "uint8",
      },
      {
        internalType: "address",
        name: "cOwner",
        type: "address",
      },
    ],
    name: "shr128",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "gtUint128",
        name: "a",
        type: "uint256",
      },
      {
        internalType: "gtUint128",
        name: "b",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "cOwner",
        type: "address",
      },
    ],
    name: "sub128",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "gtUint128",
        name: "a",
        type: "uint256",
      },
      {
        internalType: "gtUint128",
        name: "b",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "cOwner",
        type: "address",
      },
    ],
    name: "xor128",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IPodExecutor128__factory {
  static readonly abi = _abi;
  static createInterface(): IPodExecutor128Interface {
    return new Interface(_abi) as IPodExecutor128Interface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IPodExecutor128 {
    return new Contract(address, _abi, runner) as unknown as IPodExecutor128;
  }
}
