/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IPodExecutor64,
  IPodExecutor64Interface,
} from "../../../../../../contracts/pod/mpc/coti-side/IPodExecutorOps.sol/IPodExecutor64";

const _abi = [
  {
    inputs: [
      {
        internalType: "gtUint64",
        name: "a",
        type: "uint256",
      },
      {
        internalType: "gtUint64",
        name: "b",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "cOwner",
        type: "address",
      },
    ],
    name: "add64",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "gtUint64",
        name: "a",
        type: "uint256",
      },
      {
        internalType: "gtUint64",
        name: "b",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "cOwner",
        type: "address",
      },
    ],
    name: "and64",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "gtUint64",
        name: "a",
        type: "uint256",
      },
      {
        internalType: "gtUint64",
        name: "b",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "cOwner",
        type: "address",
      },
    ],
    name: "div64",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "gtUint64",
        name: "a",
        type: "uint256",
      },
      {
        internalType: "gtUint64",
        name: "b",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "cOwner",
        type: "address",
      },
    ],
    name: "eq64",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "gtUint64",
        name: "a",
        type: "uint256",
      },
      {
        internalType: "gtUint64",
        name: "b",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "cOwner",
        type: "address",
      },
    ],
    name: "ge64",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "gtUint64",
        name: "a",
        type: "uint256",
      },
      {
        internalType: "gtUint64",
        name: "b",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "cOwner",
        type: "address",
      },
    ],
    name: "gt64",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "gtUint64",
        name: "a",
        type: "uint256",
      },
      {
        internalType: "gtUint64",
        name: "b",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "cOwner",
        type: "address",
      },
    ],
    name: "le64",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "gtUint64",
        name: "a",
        type: "uint256",
      },
      {
        internalType: "gtUint64",
        name: "b",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "cOwner",
        type: "address",
      },
    ],
    name: "lt64",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "gtUint64",
        name: "a",
        type: "uint256",
      },
      {
        internalType: "gtUint64",
        name: "b",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "cOwner",
        type: "address",
      },
    ],
    name: "max64",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "gtUint64",
        name: "a",
        type: "uint256",
      },
      {
        internalType: "gtUint64",
        name: "b",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "cOwner",
        type: "address",
      },
    ],
    name: "min64",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "gtUint64",
        name: "a",
        type: "uint256",
      },
      {
        internalType: "gtUint64",
        name: "b",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "cOwner",
        type: "address",
      },
    ],
    name: "mul64",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "gtUint64",
        name: "a",
        type: "uint256",
      },
      {
        internalType: "gtUint64",
        name: "b",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "cOwner",
        type: "address",
      },
    ],
    name: "mulWrapping64",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "gtBool",
        name: "bit",
        type: "uint256",
      },
      {
        internalType: "gtUint64",
        name: "a",
        type: "uint256",
      },
      {
        internalType: "gtUint64",
        name: "b",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "cOwner",
        type: "address",
      },
    ],
    name: "mux64",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "gtUint64",
        name: "a",
        type: "uint256",
      },
      {
        internalType: "gtUint64",
        name: "b",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "cOwner",
        type: "address",
      },
    ],
    name: "ne64",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "gtUint64",
        name: "a",
        type: "uint256",
      },
      {
        internalType: "gtUint64",
        name: "b",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "cOwner",
        type: "address",
      },
    ],
    name: "or64",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "cOwner",
        type: "address",
      },
    ],
    name: "rand64",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint8",
        name: "numBits",
        type: "uint8",
      },
      {
        internalType: "address",
        name: "cOwner",
        type: "address",
      },
    ],
    name: "randBoundedBits64",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "gtUint64",
        name: "a",
        type: "uint256",
      },
      {
        internalType: "gtUint64",
        name: "b",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "cOwner",
        type: "address",
      },
    ],
    name: "rem64",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "gtUint64",
        name: "a",
        type: "uint256",
      },
      {
        internalType: "uint8",
        name: "s",
        type: "uint8",
      },
      {
        internalType: "address",
        name: "cOwner",
        type: "address",
      },
    ],
    name: "shl64",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "gtUint64",
        name: "a",
        type: "uint256",
      },
      {
        internalType: "uint8",
        name: "s",
        type: "uint8",
      },
      {
        internalType: "address",
        name: "cOwner",
        type: "address",
      },
    ],
    name: "shr64",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "gtUint64",
        name: "a",
        type: "uint256",
      },
      {
        internalType: "gtUint64",
        name: "b",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "cOwner",
        type: "address",
      },
    ],
    name: "sub64",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "gtUint64",
        name: "a",
        type: "uint256",
      },
      {
        internalType: "gtUint64",
        name: "b",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "cOwner",
        type: "address",
      },
    ],
    name: "xor64",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IPodExecutor64__factory {
  static readonly abi = _abi;
  static createInterface(): IPodExecutor64Interface {
    return new Interface(_abi) as IPodExecutor64Interface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IPodExecutor64 {
    return new Contract(address, _abi, runner) as unknown as IPodExecutor64;
  }
}
